#!/bin/bash

# rsync -avu /media/space/Videos /home/mgalgs/
# rsync -avu /home/mgalgs/Videos /media/space/

rsync -rtlvuz /media/space/Pictures /home/mgalgs/
rsync -rtlvuz /home/mgalgs/Pictures /media/space/

rsync -rtlvuz /home/mgalgs/Music /media/space/
rsync -rtlvuz /media/space/Music /home/mgalgs/
