#!/bin/bash

# rsync -avu /net/freenas/mnt/space/Videos /home/mgalgs/
# rsync -avu /home/mgalgs/Videos /net/freenas/mnt/space/

rsync -rtlvuz /net/space/media/space/Pictures /home/mgalgs/
rsync -rtlvuz /home/mgalgs/Pictures /net/space/media/space/

rsync -rtlvuz /home/mgalgs/Music /net/space/media/space/
rsync -rtlvuz /net/space/media/space/Music /home/mgalgs/
