#!/bin/sh
# emacs-mailto-handler

echo "called $0" >> /tmp/mailto-log

mailto=$1
mailto="mailto:${mailto#mailto:}"
mailto=$(printf '%s\n' "$mailto" | sed -e 's/[\"]/\\&/g')
elisp_expr="(mailto-compose-mail \"$mailto\")"

echo "elisp_expr: $elisp_expr" >> /tmp/mailto-log

emacsclient -a "" -c -n --eval "$elisp_expr" \
	'(set-window-dedicated-p (selected-window) t)'
